 Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

public class Solution {
    public char findTheDifference(String s, String t) {
        int arr1[] = new int[s.length()];
        int arr2[] = new int[t.length()];
        for(int i=0;i<s.length();i++)
            arr1[i] = (int)s.charAt(i);
        for(int i=0;i<t.length();i++)
            arr2[i] = (int)t.charAt(i);
        Arrays.sort(arr1);
        Arrays.sort(arr2);
        for(int i=0;i<s.length()||i<t.length();i++){
            if(i>=s.length())
                return (char)arr2[i];
            if(arr1[i]!=arr2[i])
                return (char)arr2[i];
        }
        return 'e';
    }
}
//using bit manipulation
public char findTheDifference(String s, String t) {
	char c = 0;
	for (int i = 0; i < s.length(); ++i) {
		c ^= s.charAt(i);
	}
	for (int i = 0; i < t.length(); ++i) {
		c ^= t.charAt(i);
	}
	return c;
}

